<?php

namespace Tests\Feature;

use App\Models\Client;
use App\Models\Company;
use App\Models\Department;
use App\Models\ProformaInvoice;
use App\Models\TaxInvoice;
use App\Models\User;
use Database\Seeders\DepartmentSeeder;
use Database\Seeders\RolePermissionSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

/**
 * Sir reported two things in the Billing section:
 * 1. The company logo wasn't appearing on either the Proforma Invoice or
 *    Tax Invoice PDF - same underlying gap as the earlier Delivery
 *    Challan fix: the templates never read Company::logo_path at all.
 * 2. No way to manually type an invoice number when creating one - it
 *    was always auto-generated by HasCompanySequenceNumber, with no
 *    override, and that auto-numbering must keep working unchanged when
 *    the new field is left blank.
 */
class BillingInvoicesTest extends TestCase
{
    use RefreshDatabase;

    private function admin(): User
    {
        $this->seed(DepartmentSeeder::class);
        $this->seed(RolePermissionSeeder::class);

        $admin = User::create([
            'name' => 'Admin', 'email' => 'admin+'.uniqid().'@example.com',
            'password' => bcrypt('password'), 'department_id' => Department::first()->id, 'is_active' => true,
        ]);
        $admin->syncRoles(['Admin']);

        return $admin;
    }

    private function company(array $overrides = []): Company
    {
        return Company::create($overrides + [
            'name' => 'Acme Builders', 'code' => 'ACME'.uniqid(),
            'tax_regime' => 'gst', 'currency' => 'INR', 'is_active' => true,
        ]);
    }

    private function client(User $admin): Client
    {
        return Client::create(['name' => 'C', 'email' => 'c+'.uniqid().'@example.com', 'phone' => '1', 'is_active' => true, 'created_by' => $admin->id]);
    }

    private function invoicePayload(Company $company, Client $client): array
    {
        return [
            'company_id' => $company->id, 'client_id' => $client->id,
            'document_date' => now()->toDateString(), 'tax_percent' => '18',
            'items' => [['name' => 'Steel Sheets', 'unit' => 'Nos', 'quantity' => '10', 'rate' => '500']],
        ];
    }

    // --- Logo ---

    public function test_the_proforma_invoice_pdf_embeds_the_companys_uploaded_logo(): void
    {
        Storage::fake('public');
        $admin = $this->admin();
        $logoPath = UploadedFile::fake()->image('logo.png', 120, 60)->store('company-logos', 'public');
        $company = $this->company(['logo_path' => $logoPath]);
        $client = $this->client($admin);

        $this->actingAs($admin)->post('/proforma-invoices', $this->invoicePayload($company, $client))->assertRedirect();
        $proformaInvoice = ProformaInvoice::firstOrFail();

        $html = view('proforma-invoices.pdf', compact('proformaInvoice'))->render();
        $this->assertStringContainsString('<img src="data:image/png;base64,', $html);
        $this->assertStringNotContainsString('>Logo<', $html);

        $response = $this->actingAs($admin)->get(route('proforma-invoices.pdf', $proformaInvoice));
        $response->assertOk();
        $this->assertSame('application/pdf', $response->headers->get('Content-Type'));
    }

    public function test_the_proforma_invoice_pdf_falls_back_to_a_placeholder_when_the_company_has_no_logo(): void
    {
        $admin = $this->admin();
        $company = $this->company();
        $client = $this->client($admin);

        $this->actingAs($admin)->post('/proforma-invoices', $this->invoicePayload($company, $client))->assertRedirect();
        $proformaInvoice = ProformaInvoice::firstOrFail();

        $html = view('proforma-invoices.pdf', compact('proformaInvoice'))->render();
        $this->assertStringNotContainsString('<img', $html);
        $this->assertStringContainsString('>Logo<', $html);
    }

    public function test_the_tax_invoice_pdf_embeds_the_companys_uploaded_logo(): void
    {
        Storage::fake('public');
        $admin = $this->admin();
        $logoPath = UploadedFile::fake()->image('logo.png', 120, 60)->store('company-logos', 'public');
        $company = $this->company(['logo_path' => $logoPath]);
        $client = $this->client($admin);

        $this->actingAs($admin)->post('/tax-invoices', $this->invoicePayload($company, $client))->assertRedirect();
        $taxInvoice = TaxInvoice::firstOrFail();

        $html = view('tax-invoices.pdf', compact('taxInvoice'))->render();
        $this->assertStringContainsString('<img src="data:image/png;base64,', $html);
        $this->assertStringNotContainsString('>Logo<', $html);

        $response = $this->actingAs($admin)->get(route('tax-invoices.pdf', $taxInvoice));
        $response->assertOk();
        $this->assertSame('application/pdf', $response->headers->get('Content-Type'));
    }

    public function test_the_tax_invoice_pdf_falls_back_to_a_placeholder_when_the_company_has_no_logo(): void
    {
        $admin = $this->admin();
        $company = $this->company();
        $client = $this->client($admin);

        $this->actingAs($admin)->post('/tax-invoices', $this->invoicePayload($company, $client))->assertRedirect();
        $taxInvoice = TaxInvoice::firstOrFail();

        $html = view('tax-invoices.pdf', compact('taxInvoice'))->render();
        $this->assertStringNotContainsString('<img', $html);
        $this->assertStringContainsString('>Logo<', $html);
    }

    // --- Manual invoice numbering ---

    public function test_proforma_invoice_still_auto_generates_a_number_when_left_blank(): void
    {
        $admin = $this->admin();
        $company = $this->company();
        $client = $this->client($admin);

        $this->actingAs($admin)->post('/proforma-invoices', $this->invoicePayload($company, $client))->assertRedirect();

        $proformaInvoice = ProformaInvoice::firstOrFail();
        $this->assertStringStartsWith('PI-'.$company->code.'-', $proformaInvoice->proforma_no);
    }

    public function test_a_manual_proforma_invoice_number_is_used_as_is(): void
    {
        $admin = $this->admin();
        $company = $this->company();
        $client = $this->client($admin);

        $this->actingAs($admin)->post('/proforma-invoices', $this->invoicePayload($company, $client) + [
            'proforma_no' => 'PI-CUSTOM-0001',
        ])->assertRedirect();

        $proformaInvoice = ProformaInvoice::firstOrFail();
        $this->assertSame('PI-CUSTOM-0001', $proformaInvoice->proforma_no);
    }

    public function test_a_duplicate_manual_proforma_invoice_number_is_rejected_with_a_validation_error(): void
    {
        $admin = $this->admin();
        $company = $this->company();
        $client = $this->client($admin);

        $this->actingAs($admin)->post('/proforma-invoices', $this->invoicePayload($company, $client) + [
            'proforma_no' => 'PI-CUSTOM-0001',
        ])->assertRedirect();

        $response = $this->actingAs($admin)->post('/proforma-invoices', $this->invoicePayload($company, $client) + [
            'proforma_no' => 'PI-CUSTOM-0001',
        ]);
        $response->assertSessionHasErrors('proforma_no');
        $this->assertSame(1, ProformaInvoice::where('proforma_no', 'PI-CUSTOM-0001')->count());
    }

    /**
     * Auto-numbering must keep reconciling against whatever is actually in
     * the table (manual numbers included) so a later auto-generated
     * number never collides with one typed in manually.
     */
    public function test_auto_numbering_still_works_correctly_after_a_manual_number_was_used(): void
    {
        $admin = $this->admin();
        $company = $this->company();
        $client = $this->client($admin);

        $this->actingAs($admin)->post('/proforma-invoices', $this->invoicePayload($company, $client) + [
            'proforma_no' => 'PI-CUSTOM-0001',
        ])->assertRedirect();

        $this->actingAs($admin)->post('/proforma-invoices', $this->invoicePayload($company, $client))->assertRedirect();

        $autoGenerated = ProformaInvoice::where('proforma_no', '!=', 'PI-CUSTOM-0001')->firstOrFail();
        $this->assertStringStartsWith('PI-'.$company->code.'-', $autoGenerated->proforma_no);
    }

    public function test_tax_invoice_still_auto_generates_a_number_when_left_blank(): void
    {
        $admin = $this->admin();
        $company = $this->company();
        $client = $this->client($admin);

        $this->actingAs($admin)->post('/tax-invoices', $this->invoicePayload($company, $client))->assertRedirect();

        $taxInvoice = TaxInvoice::firstOrFail();
        $this->assertStringStartsWith('TI-'.$company->code.'-', $taxInvoice->tax_invoice_no);
    }

    public function test_a_manual_tax_invoice_number_is_used_as_is(): void
    {
        $admin = $this->admin();
        $company = $this->company();
        $client = $this->client($admin);

        $this->actingAs($admin)->post('/tax-invoices', $this->invoicePayload($company, $client) + [
            'tax_invoice_no' => 'TI-CUSTOM-0001',
        ])->assertRedirect();

        $taxInvoice = TaxInvoice::firstOrFail();
        $this->assertSame('TI-CUSTOM-0001', $taxInvoice->tax_invoice_no);
    }

    public function test_a_duplicate_manual_tax_invoice_number_is_rejected_with_a_validation_error(): void
    {
        $admin = $this->admin();
        $company = $this->company();
        $client = $this->client($admin);

        $this->actingAs($admin)->post('/tax-invoices', $this->invoicePayload($company, $client) + [
            'tax_invoice_no' => 'TI-CUSTOM-0001',
        ])->assertRedirect();

        $response = $this->actingAs($admin)->post('/tax-invoices', $this->invoicePayload($company, $client) + [
            'tax_invoice_no' => 'TI-CUSTOM-0001',
        ]);
        $response->assertSessionHasErrors('tax_invoice_no');
        $this->assertSame(1, TaxInvoice::where('tax_invoice_no', 'TI-CUSTOM-0001')->count());
    }

    /**
     * The edit form must never expose the number field at all - editing
     * an invoice (even one that was manually numbered) must never be able
     * to blank out or change its number.
     */
    public function test_the_edit_form_does_not_expose_the_invoice_number_field(): void
    {
        $admin = $this->admin();
        $company = $this->company();
        $client = $this->client($admin);

        $this->actingAs($admin)->post('/proforma-invoices', $this->invoicePayload($company, $client))->assertRedirect();
        $proformaInvoice = ProformaInvoice::firstOrFail();
        $originalNumber = $proformaInvoice->proforma_no;

        $this->actingAs($admin)->get("/proforma-invoices/{$proformaInvoice->id}/edit")
            ->assertOk()
            ->assertDontSee('name="proforma_no"', false);

        $this->actingAs($admin)->put("/proforma-invoices/{$proformaInvoice->id}", $this->invoicePayload($company, $client))
            ->assertRedirect();

        $this->assertSame($originalNumber, $proformaInvoice->fresh()->proforma_no);
    }
}
